CC=m6809-unknown-gcc
CFLAGS=-Os -DFUZIX
IFLAGS=-I/home/n6il/src/FUZIX/Library/include -I/home/n6il/src/FUZIX/Library/include/6809
LFLAGS=-nostdlib -L/home/n6il/src/FUZIX/Library/libs 
LIBS=-lc6809 -lgcc

OBJS=sdccmdr.o string.o libsdc.o commsdc.o irq.o
SCREEN=fuzix/screen.o

all: sdccmdr

screen: 
	make -C fuzix

sdccmdr: $(OBJS) screen
	$(CC) $(CFLAGS) -o sdccmdr $(OBJS) $(SCREEN) $(LFLAGS) $(LIBS)

%.o: %.S
	$(CC) $(CFLAGS) $(IFLAGS) -c $<

%.o: %.c
	$(CC) $(CFLAGS) $(IFLAGS) -c $<
